version: '3.8'

services:
  auto-dev-bridge:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: auto-dev-bridge
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - auto-dev-network

  # Development client (for testing)
  auto-dev-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: auto-dev-client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:3001
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    depends_on:
      - auto-dev-bridge
    restart: unless-stopped
    networks:
      - auto-dev-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: auto-dev-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auto-dev-bridge
      - auto-dev-client
    restart: unless-stopped
    networks:
      - auto-dev-network

networks:
  auto-dev-network:
    driver: bridge

volumes:
  auto_dev_data:
    driver: local